/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "clavesRPC.h"

bool_t
xdr_Paquete_rpc (XDR *xdrs, Paquete_rpc *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->x))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->y))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->z))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_KeyArg (XDR *xdrs, KeyArg *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->key, 256))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_TuplaArg (XDR *xdrs, TuplaArg *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->key, 256))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->value1, 256))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->N_value2))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->V_value2.V_value2_val, (u_int *) &objp->V_value2.V_value2_len, 32,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	 if (!xdr_Paquete_rpc (xdrs, &objp->value3))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_GetValueResult (XDR *xdrs, GetValueResult *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->value1, 256))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->N_value2))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->V_value2.V_value2_val, (u_int *) &objp->V_value2.V_value2_len, 32,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	 if (!xdr_Paquete_rpc (xdrs, &objp->value3))
		 return FALSE;
	return TRUE;
}
