/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CLAVESRPC_H_RPCGEN
#define _CLAVESRPC_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


struct Paquete_rpc {
	int x;
	int y;
	int z;
};
typedef struct Paquete_rpc Paquete_rpc;

struct KeyArg {
	char *key;
};
typedef struct KeyArg KeyArg;

struct TuplaArg {
	char *key;
	char *value1;
	int N_value2;
	struct {
		u_int V_value2_len;
		float *V_value2_val;
	} V_value2;
	Paquete_rpc value3;
};
typedef struct TuplaArg TuplaArg;

struct GetValueResult {
	int status;
	char *value1;
	int N_value2;
	struct {
		u_int V_value2_len;
		float *V_value2_val;
	} V_value2;
	Paquete_rpc value3;
};
typedef struct GetValueResult GetValueResult;

#define CLAVES_PROG 0x20000001
#define CLAVES_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define DESTROY 1
extern  enum clnt_stat destroy_1(int *, CLIENT *);
extern  bool_t destroy_1_svc(int *, struct svc_req *);
#define SET_VALUE 2
extern  enum clnt_stat set_value_1(TuplaArg , int *, CLIENT *);
extern  bool_t set_value_1_svc(TuplaArg , int *, struct svc_req *);
#define GET_VALUE 3
extern  enum clnt_stat get_value_1(KeyArg , GetValueResult *, CLIENT *);
extern  bool_t get_value_1_svc(KeyArg , GetValueResult *, struct svc_req *);
#define MODIFY_VALUE 4
extern  enum clnt_stat modify_value_1(TuplaArg , int *, CLIENT *);
extern  bool_t modify_value_1_svc(TuplaArg , int *, struct svc_req *);
#define DELETE_KEY 5
extern  enum clnt_stat delete_key_1(KeyArg , int *, CLIENT *);
extern  bool_t delete_key_1_svc(KeyArg , int *, struct svc_req *);
#define EXIST 6
extern  enum clnt_stat exist_1(KeyArg , int *, CLIENT *);
extern  bool_t exist_1_svc(KeyArg , int *, struct svc_req *);
extern int claves_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define DESTROY 1
extern  enum clnt_stat destroy_1();
extern  bool_t destroy_1_svc();
#define SET_VALUE 2
extern  enum clnt_stat set_value_1();
extern  bool_t set_value_1_svc();
#define GET_VALUE 3
extern  enum clnt_stat get_value_1();
extern  bool_t get_value_1_svc();
#define MODIFY_VALUE 4
extern  enum clnt_stat modify_value_1();
extern  bool_t modify_value_1_svc();
#define DELETE_KEY 5
extern  enum clnt_stat delete_key_1();
extern  bool_t delete_key_1_svc();
#define EXIST 6
extern  enum clnt_stat exist_1();
extern  bool_t exist_1_svc();
extern int claves_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Paquete_rpc (XDR *, Paquete_rpc*);
extern  bool_t xdr_KeyArg (XDR *, KeyArg*);
extern  bool_t xdr_TuplaArg (XDR *, TuplaArg*);
extern  bool_t xdr_GetValueResult (XDR *, GetValueResult*);

#else /* K&R C */
extern bool_t xdr_Paquete_rpc ();
extern bool_t xdr_KeyArg ();
extern bool_t xdr_TuplaArg ();
extern bool_t xdr_GetValueResult ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CLAVESRPC_H_RPCGEN */
